# docker-compose -f docker-compose.build.yml build --no-cache
# docker-compose -f docker-compose.build.yml push

version: '3.5'
services:
  dotnetcore-builder:
    image: tjmt/dotnetcore:runtime
    build: 
      context: .
      dockerfile: Dockerfile      
      args:
        TimeZone: "America/Cuiaba" #OPCIONAL: default = America/Cuiaba
        Language: "pt_BR" #OPCIONAL: default = pt_BR
        Unicode: "UTF-8" #OPCIONAL: default = UTF-8
