# docker-compose -f docker-compose.build.yml build
# docker-compose -f docker-compose.build.yml push

version: '3.5'
services:
  dotnetcore-builder:
    image: ${REGISTRY}dotnetcore:runtime
    build: 
      context: .
      dockerfile: Dockerfile      
      args:
        TimeZone: "America/Cuiaba"